# https://www.jaegertracing.io/docs/2.12/deployment/configuration/
# https://www.jaegertracing.io/docs/2.12/storage/badger/
extensions:
  jaeger_storage:
    backends:
      main_storage:
        badger:
          directories:
            keys: /tmp/badger/keys
            values: /tmp/badger/data
          ephemeral: false
          consistency: true
          maintenance_interval: 5m
  jaeger_query:
    storage:
      traces: main_storage

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: main_storage

service:
  extensions: [jaeger_storage, jaeger_query]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]
