[build]
publish = "docs/.vitepress/dist"
command = "pnpm ci:docs"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF docs/ package.json pnpm-lock.yaml"

[build.environment]
NODE_VERSION = "24"
# don't need playwright for docs build
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"
# https://github.com/nodejs/corepack/issues/612#issuecomment-2631462297
COREPACK_INTEGRITY_KEYS = '{"npm":[{"expires":"2025-01-29T00:00:00.000Z","keyid":"SHA256:jl3bwswu80PjjokCgh0o2w5c2U4LhQAE57gj9cz1kzA","keytype":"ecdsa-sha2-nistp256","scheme":"ecdsa-sha2-nistp256","key":"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1Olb3zMAFFxXKHiIkQO5cJ3Yhl5i6UPp+IhuteBJbuHcA5UogKo0EWtlWwW6KSaKoTNEYL7JlCQiVnkhBktUgg=="},{"expires":null,"keyid":"SHA256:DhQ8wR5APBvFHLF/+Tc+AYvPOdTpcIDqOhxsBHRwC7U","keytype":"ecdsa-sha2-nistp256","scheme":"ecdsa-sha2-nistp256","key":"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEY6Ya7W++7aUPzvMTrezH6Ycx3c+HOKYCcNGybJZSCJq/fd7Qa8uuAKtdIkUQtQiEKERhAmE5lMMJhP8OkDOa2g=="}]}'

[[redirects]]
from = "/new"
to = "https://stackblitz.com/fork/github/vitest-dev/vitest/tree/main/examples/basic?initialPath=__vitest__/"
status = 302

[[redirects]]
from = "/vscode"
to = "https://marketplace.visualstudio.com/items?itemName=vitest.explorer"
status = 302

[[redirects]]
from = "/config/file"
to = "/config/"
status = 301

[[redirects]]
from = "/config/browser"
to = "/config/browser/enabled"
status = 301

[[redirects]]
from = "/guide/workspace"
to = "/guide/projects"
status = 301

[[redirects]]
from = "/advanced/api"
to = "/guide/advanced"
status = 301

[[redirects]]
from = "/advanced/api/*"
to = "/api/advanced/:splat"
status = 301

[[redirects]]
from = "/advanced/*"
to = "/guide/advanced/:splat"
status = 301

[[redirects]]
from = "/guide/workspace.html"
to = "/guide/projects"
status = 301

[[redirects]]
from = "/guide/browser/context"
to = "/api/browser/context"
status = 301

[[redirects]]
from = "/guide/browser/interactivity-api"
to = "/api/browser/interactivity"
status = 301

[[redirects]]
from = "/guide/browser/locators"
to = "/api/browser/locators"
status = 301

[[redirects]]
from = "/guide/browser/assertion-api"
to = "/api/browser/assertions"
status = 301

[[redirects]]
from = "/guide/browser/commands"
to = "/api/browser/commands"
status = 301

[[redirects]]
from = "/guide/browser/playwright"
to = "/config/browser/playwright"
status = 301

[[redirects]]
from = "/guide/browser/webdriverio"
to = "/config/browser/webdriverio"
status = 301

[[redirects]]
from = "/api/"
to = "/api/test"
status = 301

[[headers]]
for = "/manifest.webmanifest"

[headers.values]
Content-Type = "application/manifest+json"
